### PR TITLE
initial commit:

### PR DESCRIPTION
**Pull request by Ekko1112**
- review source code for futher changes

### CODE REVIEW

**Review by narraressan — CHANGES_REQUESTED** [review]
@Ekko1112 
Wrong branch naming. 

Please follow the guidelines for naming branches.
```correction: feature/41906445-login-register```
** must contain 1 slash only

Kindly edit PR to follow the template.
check our guidelines at `https://github.com/devph-git/pos-system/blob/dev/PULL_REQUEST.md`
View as a raw file and copy-paste to PR description.

**Comment by dgualvez** [comment]
@narraressan is this too much changes for the initial commit?

**Comment by narraressan** [comment]
> @narraressan is this too much changes for the initial commit?

correct, we should observe micro commits in the future.

**Review by dgualvez — CHANGES_REQUESTED** [review]
Missing .env.example file.

**Pull request closed without merging**
